### ISSUE TITLE
i cannot compile your project

### ISSUE THREAD

**Issue by BatuhanGnday** [yldrma9/ConsoleAppMacOS#1]
the project has some errors that cause the failure to compile the project.

**Comment by repfly** [comment]
even we cannot

**Comment by repfly** [comment]
I think you are missing some points. can you send the errors?

**Comment by BatuhanGnday** [comment]
i know lul

**Comment by BatuhanGnday** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32869414/68021786-755ebf80-fcb3-11e9-980d-b1537c286957.png">

**Comment by repfly** [comment]
there can't be a creature without mistakes. just leave the issue. thanks.

**Comment by BatuhanGnday** [comment]
well gg

**Comment by repfly** [comment]
bye

**Comment by BatuhanGnday** [comment]
ßß

**Comment by repfly** [comment]
brother. can you elleşmez misin?

**Comment by BatuhanGnday** [comment]
noldu ya foton gitti
